FROM eclipse-temurin:20-jre
ENTRYPOINT java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version 2>/dev/null \
    | grep -Ewi "MaxHeapSize|maxram" \ 
    | awk '{ if($4 >= 1024*1024*1024) print $2, $3, $4/(1024*1024*1024) " GB"; else if($4 >= 1024*1024) print $2, $3, $4/(1024*1024) " MB"; else if($4 >= 1024) print $2, $3, $4/1024 " KB"; else print $2, $3, $4 " Bytes"; }' \
    && java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version 2>/dev/null \
    | grep -Ewi "ThreadStackSize|VMThreadStackSize" \ 
    | awk '{ if($4 >= 1024*1024) print $2, $3, $4/(1024*1024) " GB"; else if($4 >= 1024) print $2, $3, $4/1024 " MB"; else print $2, $3, $4 " KB"; }'